### ISSUE TITLE
Docker cache invalidates apt-get update

### ISSUE THREAD

**Issue by malex984** [malex984/dockapp#13]
Most of our Dockerfiles start with identical "header":

```
FROM malex984/dockapp:base
MAINTAINER Oleksandr Motsak <malex984@googlemail.com>
RUN DEBIAN_FRONTEND=noninteractive apt-get -y update
```

which seems to confuse docker build to use its cache instead of performing `apt-get -y update` as desired... (which leads to outdated package repository data)

Manual workarounds for cache miss: 
1. swap MAINTAINER and RUN
2. add/remove `-q`, e.g. `RUN DEBIAN_FRONTEND=noninteractive apt-get -y -q update`

Q: is there a way to force docker build to ALWAYS run that update (without completely switching its cache usage)?

**Comment by porst17** [comment]
A: Updating the package cache and installing belong together. The second is invalid without the first. Hence, combine the `apt-get update` and `apt-get install` lines into one. Then the cache for this line contains the whole thing. Also you have to use version pinning for each package. If you change the version number for a package, the cache becomes invalid and will be rebuild.

Example:

```
RUN DEBIAN_FRONTEND=noninteractive apt-get -y update && apt-get -y install bash=4.2* zsh=5.3*
```

When you want to upgrade to Bash 4.3, simply change the line to

```
RUN DEBIAN_FRONTEND=noninteractive apt-get -y update && apt-get -y install bash=4.3* zsh=5.3*
```

and the cache will be rebuild.

Note, that this version pinning can break Dockerfiles. If a certain version is not available in the repository anymore, the Dockerfile won't build. But I think it's actually an advantage since unnoticed changes in the version can also change the behavior of the final image, leading to unpredictable results (kind of the opposite we want to achieve with Docker). So it's better to manually update the version in the Dockerfile, test it and commit again to be on the safe side. See also #4.

**Comment by malex984** [comment]
I think this issue is not a problem anymore as we switch to running apt-get update && install within the very same Dockerfile-RUN instruction...?

**Comment by porst17** [comment]
Please either reference the issue in the commit that fixes this or reference the commit here in the issue tracker. Afterwards the issue can be closed.

**Comment by malex984** [comment]
Ok, I fixed all the remaining Dockerfile's to abide to that requirement in 17da3e962973349b5a6ab5843b553f16f41e173d
