### ISSUE TITLE
Do not use latest tag to reference base images

### ISSUE THREAD

**Issue by porst17** [malex984/dockapp#54]
The `FROM` command in a `Dockerfile` should always reference a version tag and not `latest`. The meaning of `latest` changes over time and if you have an old version of an image on your machine that is also tagged with `latest`, derived images may just not build and run properly because the base layers contain unexpected outdated stuff.

This is also very important if we have to deliver updates and bug fixes in a production environment.

**Comment by porst17** [comment]
This is also related to #4.

**Comment by porst17** [comment]
The current automatic build on docker hub only builds two version of the images: `master` and `devel`. The `Dockerfile`s do not specify which tag should be used so a build hook is used to work around this.

It is trivial to properly manage dependencies between `Dockerfile`s by just adding the version tag in `FROM`. It looks like docker hub can automatically pick up git-tags as well and build and tag the corresponding images (but this has to be tested). In order to continue having separate a image for `devel` (`master` is not needed because it should always belong to a tag), the build hook could replace the version tags with a `devel` tag when the `devel` branch is build.

**Comment by malex984** [comment]
Currently we use [/images/*/hooks/build](https://github.com/hilbert/hilbert-docker-images/blob/devel/helpers/docker-build-hook), which should automate building (both locally and on DockerHub). 

In particular that script should replace lines like `FROM hilbert/baseimagename` (in corresponding `Dockerfile`) into `FROM hilbert/baseimagename:SOMETAG`, where `SOMETAG` has to be specified by the build system (i.e. due to target `IMAGE_NAME`).

It will not happen if one specify FROM image with an explicit tag.

**Comment by malex984** [comment]
That means what when DockerHub builds `hilbert/gui:SOMETAG` it will (using our build hook) base it on top of `hilbert/base:SOMETAG` (since `/gui` is based on `/base`), where `SOMETAG` may be for example `latest` or `devel` or `master` or any version tag.

**Comment by porst17** [comment]
So in theory, it should just work once automatic building for tags is configured on docker hub, right?

**Comment by malex984** [comment]
for completeness here is the way to configure DockerHub to deal with git tags: https://stackoverflow.com/a/44796846
